name: repolint
description: A GitHub Action that checks the repository for consistency
author: samdouble
inputs:
  github-token:
    description: GitHub token for API access
    required: true
    default: ${{ github.token }}
runs:
  using: node20
  main: dist/index.js
