name: repolint
description: A GitHub Action that checks the repository for consistency
author: samdouble
inputs:
  github-token:
    description: GitHub token for API access
    required: false
    default: ${{ github.token }}
permissions:
  contents: read
runs:
  using: node20
  main: action/dist/index.js
